#ifndef PINS_HPP
#define PINS_HPP

#define UNDEFINED_PIN 99

#define PIN_OLED_CS 17
#define PIN_OLED_DC 2
#define PIN_OLED_RESET 32

#define PIN_ENCBTN1 UNDEFINED_PIN
#define PIN_ENCBTN2 22
#define PIN_ENCBTN3 21
#define PIN_ENCBTN4 19

#define PIN_ENC1A UNDEFINED_PIN
#define PIN_ENC1B UNDEFINED_PIN
#define PIN_ENC2A UNDEFINED_PIN
#define PIN_ENC2B UNDEFINED_PIN
#define PIN_ENC3A UNDEFINED_PIN
#define PIN_ENC3B UNDEFINED_PIN
#define PIN_ENC4A 4
#define PIN_ENC4B 15

#endif