#ifndef PINS_HPP
#define PINS_HPP

#define UNDEFINED_PIN 99

#define PIN_SLD_1 UNDEFINED_PIN
#define PIN_SLD_2 UNDEFINED_PIN
#define PIN_SLD_3 UNDEFINED_PIN

#define PIN_ENC1A UNDEFINED_PIN
#define PIN_ENC1B UNDEFINED_PIN
#define PIN_ENC2A UNDEFINED_PIN
#define PIN_ENC2B UNDEFINED_PIN
#define PIN_ENC3A UNDEFINED_PIN
#define PIN_ENC3B UNDEFINED_PIN
#define PIN_ENC4A UNDEFINED_PIN
#define PIN_ENC4B UNDEFINED_PIN

#endif